### ISSUE TITLE
locally stored seed

### ISSUE THREAD

**Issue by pickles4nickels** [akirattii/akirattii.github.io#1]
I generated a new seed for the wallet which generated a new address. I was not expecting a new address to be generated so I did not make a copy of the original seed. My ripple is stored on the original address. 
How can the seed for the original address be recovered from the local storage?
I have a backup of the wallet in its original state on Time Machine (OSX).

**Comment by akirattii** [comment]
@pickles4nickels Your local secret seed is encrypted by `AES192` encryption. so you can recover it from your passphrase if there is the encrypted data on your machine yet. It is stored on the localstorage of chrome, its path is depending on your machine. Please google to know about localstorage of chrome. 
I hope it will be helpful for you.
