### ISSUE TITLE
Missing XRP

### ISSUE THREAD

**Issue by leewriter1** [akirattii/akirattii.github.io#2]
I should have 942.82 units of XRP in in my Ripple 0.8.0 wallet but the balance is 0. I hadn't checked my account for about ninety days so unfortunately I can't pinpoint what date the issue first appeared. My 
address is r41SiB8px5YnA1n6iHPJ3X7ZyxJNfdWwp9. I was very careful to keep track of my secret seed in an Excel spreadsheet so I'm sure that I entered the correct one. Please let me know what you find out and how I can recover my XRP. Thank you.

**Comment by akirattii** [comment]
Hey @leewriter1 

Your address `r41SiB8px5YnA1n6iHPJ3X7ZyxJNfdWwp9` is `Account Not Found`, has no XRP and no tx history. It's not activated because it have never had some any funds yet. Try to check your address by yourself here: https://xrpcharts.ripple.com/#/graph

> I should have 942.82 units of XRP in in my Ripple 0.8.0

How do you know it? 
On both LiveNet and TestNet, your address status is `actNotFound` (Account Not Found): 
```
// TestNet:
$ curl -XPOST -H "application/json" -d '''
{"method":"account_info","params":[{"account":"r41SiB8px5YnA1n6iHPJ3X7ZyxJNfdWwp9"}]}
''' https://s.altnet.rippletest.net:51234

{"result":{"account":"r41SiB8px5YnA1n6iHPJ3X7ZyxJNfdWwp9","error":"actNotFound","error_code":19,"error_message":"Account not found.","ledger_current_index":9687635,"request":{"account":"r41SiB8px5YnA1n6iHPJ3X7ZyxJNfdWwp9","command":"account_info"},"status":"error","validated":false}}

// LiveNet:
$ curl -XPOST -H "application/json" -d '''
{"method":"account_info","params":[{"account":"r41SiB8px5YnA1n6iHPJ3X7ZyxJNfdWwp9"}]}
''' https://s1.ripple.com:51234

{"result":{"account":"r41SiB8px5YnA1n6iHPJ3X7ZyxJNfdWwp9","error":"actNotFound","error_code":19,"error_message":"Account not found.","ledger_current_index":39127294,"request":{"account":"r41SiB8px5YnA1n6iHPJ3X7ZyxJNfdWwp9","command":"account_info"},"status":"error","validated":false}}
```

**Comment by leewriter1** [comment]
Unfortunately I did not save screenshots of when I had units in my account. I kept track of my balance on a spreadsheet so I know that's what it is supposed to be. So apparently I'm out of luck. Great. Thanks.

​Best Regards,​
Lee A. Eide
​Phone #: 601-212-5485

www.drofbadology.com<http://www.drofbadology.com>
Author of :


"The (Breaking) Bad Path to Enlightenment & Sobriety: Learn from Walter White's Mistakes" -- www.smashwords.com/view/746881<http://www.smashwords.com/view/746881>

and

"Overcome Any Personal  Obstacle, Including Alcoholism, by Understanding Your Ego" -- www.lulu.com/spotlight/leewriter<http://www.lulu.com/spotlight/leewriter>

and

"Dead Man's Plan" , a spiritual suspense drama featuring Lee Wyatt, available at https://www.amazon.com/Dead-Mans-Plan-Lee-Eide/dp/1441523219
















































​​
Lee A. Eide
www.drofbadology.com​​

Author of :​
"The (Breaking) Bad Path to Enlightenment & Sobriety: Learn from Walter White's Mistakes" -- www.smashwords.com/view/746881<http://www.smashwords.com/view/746881>
and
"Overcome Any Personal  Obstacle, Including Alcoholism, by Understanding Your Ego" -- www.lulu.com/spotlight/leewriter<http://www.lulu.com/spotlight/leewriter>
and
"Dead Man's Plan" , a spiritual suspense drama featuring Lee Wyatt, available at https://www.amazon.com/Dead-Mans-Plan-Lee-Eide/dp/1441523219

________________________________
